/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.sachet;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class OrderDto extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -153907526876039344L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"OrderDto\",\"namespace\":\"com.sachet\",\"fields\":[{\"name\":\"count\",\"type\":\"int\"},{\"name\":\"productId\",\"type\":\"long\"},{\"name\":\"status\",\"type\":\"string\"},{\"name\":\"sellerEmail\",\"type\":\"string\"},{\"name\":\"buyerEmail\",\"type\":\"string\"},{\"name\":\"id\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<OrderDto> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<OrderDto> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<OrderDto> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<OrderDto> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<OrderDto> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this OrderDto to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a OrderDto from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a OrderDto instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static OrderDto fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private int count;
  private long productId;
  private java.lang.CharSequence status;
  private java.lang.CharSequence sellerEmail;
  private java.lang.CharSequence buyerEmail;
  private long id;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public OrderDto() {}

  /**
   * All-args constructor.
   * @param count The new value for count
   * @param productId The new value for productId
   * @param status The new value for status
   * @param sellerEmail The new value for sellerEmail
   * @param buyerEmail The new value for buyerEmail
   * @param id The new value for id
   */
  public OrderDto(java.lang.Integer count, java.lang.Long productId, java.lang.CharSequence status, java.lang.CharSequence sellerEmail, java.lang.CharSequence buyerEmail, java.lang.Long id) {
    this.count = count;
    this.productId = productId;
    this.status = status;
    this.sellerEmail = sellerEmail;
    this.buyerEmail = buyerEmail;
    this.id = id;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return count;
    case 1: return productId;
    case 2: return status;
    case 3: return sellerEmail;
    case 4: return buyerEmail;
    case 5: return id;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: count = (java.lang.Integer)value$; break;
    case 1: productId = (java.lang.Long)value$; break;
    case 2: status = (java.lang.CharSequence)value$; break;
    case 3: sellerEmail = (java.lang.CharSequence)value$; break;
    case 4: buyerEmail = (java.lang.CharSequence)value$; break;
    case 5: id = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'count' field.
   * @return The value of the 'count' field.
   */
  public int getCount() {
    return count;
  }


  /**
   * Sets the value of the 'count' field.
   * @param value the value to set.
   */
  public void setCount(int value) {
    this.count = value;
  }

  /**
   * Gets the value of the 'productId' field.
   * @return The value of the 'productId' field.
   */
  public long getProductId() {
    return productId;
  }


  /**
   * Sets the value of the 'productId' field.
   * @param value the value to set.
   */
  public void setProductId(long value) {
    this.productId = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public java.lang.CharSequence getStatus() {
    return status;
  }


  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(java.lang.CharSequence value) {
    this.status = value;
  }

  /**
   * Gets the value of the 'sellerEmail' field.
   * @return The value of the 'sellerEmail' field.
   */
  public java.lang.CharSequence getSellerEmail() {
    return sellerEmail;
  }


  /**
   * Sets the value of the 'sellerEmail' field.
   * @param value the value to set.
   */
  public void setSellerEmail(java.lang.CharSequence value) {
    this.sellerEmail = value;
  }

  /**
   * Gets the value of the 'buyerEmail' field.
   * @return The value of the 'buyerEmail' field.
   */
  public java.lang.CharSequence getBuyerEmail() {
    return buyerEmail;
  }


  /**
   * Sets the value of the 'buyerEmail' field.
   * @param value the value to set.
   */
  public void setBuyerEmail(java.lang.CharSequence value) {
    this.buyerEmail = value;
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public long getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(long value) {
    this.id = value;
  }

  /**
   * Creates a new OrderDto RecordBuilder.
   * @return A new OrderDto RecordBuilder
   */
  public static com.sachet.OrderDto.Builder newBuilder() {
    return new com.sachet.OrderDto.Builder();
  }

  /**
   * Creates a new OrderDto RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new OrderDto RecordBuilder
   */
  public static com.sachet.OrderDto.Builder newBuilder(com.sachet.OrderDto.Builder other) {
    if (other == null) {
      return new com.sachet.OrderDto.Builder();
    } else {
      return new com.sachet.OrderDto.Builder(other);
    }
  }

  /**
   * Creates a new OrderDto RecordBuilder by copying an existing OrderDto instance.
   * @param other The existing instance to copy.
   * @return A new OrderDto RecordBuilder
   */
  public static com.sachet.OrderDto.Builder newBuilder(com.sachet.OrderDto other) {
    if (other == null) {
      return new com.sachet.OrderDto.Builder();
    } else {
      return new com.sachet.OrderDto.Builder(other);
    }
  }

  /**
   * RecordBuilder for OrderDto instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<OrderDto>
    implements org.apache.avro.data.RecordBuilder<OrderDto> {

    private int count;
    private long productId;
    private java.lang.CharSequence status;
    private java.lang.CharSequence sellerEmail;
    private java.lang.CharSequence buyerEmail;
    private long id;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.sachet.OrderDto.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.count)) {
        this.count = data().deepCopy(fields()[0].schema(), other.count);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.productId)) {
        this.productId = data().deepCopy(fields()[1].schema(), other.productId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.status)) {
        this.status = data().deepCopy(fields()[2].schema(), other.status);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.sellerEmail)) {
        this.sellerEmail = data().deepCopy(fields()[3].schema(), other.sellerEmail);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.buyerEmail)) {
        this.buyerEmail = data().deepCopy(fields()[4].schema(), other.buyerEmail);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.id)) {
        this.id = data().deepCopy(fields()[5].schema(), other.id);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing OrderDto instance
     * @param other The existing instance to copy.
     */
    private Builder(com.sachet.OrderDto other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.count)) {
        this.count = data().deepCopy(fields()[0].schema(), other.count);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.productId)) {
        this.productId = data().deepCopy(fields()[1].schema(), other.productId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.status)) {
        this.status = data().deepCopy(fields()[2].schema(), other.status);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.sellerEmail)) {
        this.sellerEmail = data().deepCopy(fields()[3].schema(), other.sellerEmail);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.buyerEmail)) {
        this.buyerEmail = data().deepCopy(fields()[4].schema(), other.buyerEmail);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.id)) {
        this.id = data().deepCopy(fields()[5].schema(), other.id);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'count' field.
      * @return The value.
      */
    public int getCount() {
      return count;
    }


    /**
      * Sets the value of the 'count' field.
      * @param value The value of 'count'.
      * @return This builder.
      */
    public com.sachet.OrderDto.Builder setCount(int value) {
      validate(fields()[0], value);
      this.count = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'count' field has been set.
      * @return True if the 'count' field has been set, false otherwise.
      */
    public boolean hasCount() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'count' field.
      * @return This builder.
      */
    public com.sachet.OrderDto.Builder clearCount() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'productId' field.
      * @return The value.
      */
    public long getProductId() {
      return productId;
    }


    /**
      * Sets the value of the 'productId' field.
      * @param value The value of 'productId'.
      * @return This builder.
      */
    public com.sachet.OrderDto.Builder setProductId(long value) {
      validate(fields()[1], value);
      this.productId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'productId' field has been set.
      * @return True if the 'productId' field has been set, false otherwise.
      */
    public boolean hasProductId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'productId' field.
      * @return This builder.
      */
    public com.sachet.OrderDto.Builder clearProductId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public java.lang.CharSequence getStatus() {
      return status;
    }


    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public com.sachet.OrderDto.Builder setStatus(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.status = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public com.sachet.OrderDto.Builder clearStatus() {
      status = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'sellerEmail' field.
      * @return The value.
      */
    public java.lang.CharSequence getSellerEmail() {
      return sellerEmail;
    }


    /**
      * Sets the value of the 'sellerEmail' field.
      * @param value The value of 'sellerEmail'.
      * @return This builder.
      */
    public com.sachet.OrderDto.Builder setSellerEmail(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.sellerEmail = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'sellerEmail' field has been set.
      * @return True if the 'sellerEmail' field has been set, false otherwise.
      */
    public boolean hasSellerEmail() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'sellerEmail' field.
      * @return This builder.
      */
    public com.sachet.OrderDto.Builder clearSellerEmail() {
      sellerEmail = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'buyerEmail' field.
      * @return The value.
      */
    public java.lang.CharSequence getBuyerEmail() {
      return buyerEmail;
    }


    /**
      * Sets the value of the 'buyerEmail' field.
      * @param value The value of 'buyerEmail'.
      * @return This builder.
      */
    public com.sachet.OrderDto.Builder setBuyerEmail(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.buyerEmail = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'buyerEmail' field has been set.
      * @return True if the 'buyerEmail' field has been set, false otherwise.
      */
    public boolean hasBuyerEmail() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'buyerEmail' field.
      * @return This builder.
      */
    public com.sachet.OrderDto.Builder clearBuyerEmail() {
      buyerEmail = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public long getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.sachet.OrderDto.Builder setId(long value) {
      validate(fields()[5], value);
      this.id = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.sachet.OrderDto.Builder clearId() {
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public OrderDto build() {
      try {
        OrderDto record = new OrderDto();
        record.count = fieldSetFlags()[0] ? this.count : (java.lang.Integer) defaultValue(fields()[0]);
        record.productId = fieldSetFlags()[1] ? this.productId : (java.lang.Long) defaultValue(fields()[1]);
        record.status = fieldSetFlags()[2] ? this.status : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.sellerEmail = fieldSetFlags()[3] ? this.sellerEmail : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.buyerEmail = fieldSetFlags()[4] ? this.buyerEmail : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.id = fieldSetFlags()[5] ? this.id : (java.lang.Long) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<OrderDto>
    WRITER$ = (org.apache.avro.io.DatumWriter<OrderDto>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<OrderDto>
    READER$ = (org.apache.avro.io.DatumReader<OrderDto>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.count);

    out.writeLong(this.productId);

    out.writeString(this.status);

    out.writeString(this.sellerEmail);

    out.writeString(this.buyerEmail);

    out.writeLong(this.id);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.count = in.readInt();

      this.productId = in.readLong();

      this.status = in.readString(this.status instanceof Utf8 ? (Utf8)this.status : null);

      this.sellerEmail = in.readString(this.sellerEmail instanceof Utf8 ? (Utf8)this.sellerEmail : null);

      this.buyerEmail = in.readString(this.buyerEmail instanceof Utf8 ? (Utf8)this.buyerEmail : null);

      this.id = in.readLong();

    } else {
      for (int i = 0; i < 6; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.count = in.readInt();
          break;

        case 1:
          this.productId = in.readLong();
          break;

        case 2:
          this.status = in.readString(this.status instanceof Utf8 ? (Utf8)this.status : null);
          break;

        case 3:
          this.sellerEmail = in.readString(this.sellerEmail instanceof Utf8 ? (Utf8)this.sellerEmail : null);
          break;

        case 4:
          this.buyerEmail = in.readString(this.buyerEmail instanceof Utf8 ? (Utf8)this.buyerEmail : null);
          break;

        case 5:
          this.id = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










