/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.sachet;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class OrderDto extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7834100810242072112L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"OrderDto\",\"namespace\":\"com.sachet\",\"fields\":[{\"name\":\"count\",\"type\":\"int\"},{\"name\":\"productId\",\"type\":\"long\"},{\"name\":\"status\",\"type\":\"string\"},{\"name\":\"sellerEmail\",\"type\":\"string\"},{\"name\":\"buyerEmail\",\"type\":\"string\"},{\"name\":\"orderId\",\"type\":\"long\"},{\"name\":\"expiresAt\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\",\"default\":null}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<OrderDto> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<OrderDto> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<OrderDto> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<OrderDto> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<OrderDto> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this OrderDto to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a OrderDto from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a OrderDto instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static OrderDto fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private int count;
  private long productId;
  private java.lang.CharSequence status;
  private java.lang.CharSequence sellerEmail;
  private java.lang.CharSequence buyerEmail;
  private long orderId;
  private java.time.Instant expiresAt;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public OrderDto() {}

  /**
   * All-args constructor.
   * @param count The new value for count
   * @param productId The new value for productId
   * @param status The new value for status
   * @param sellerEmail The new value for sellerEmail
   * @param buyerEmail The new value for buyerEmail
   * @param orderId The new value for orderId
   * @param expiresAt The new value for expiresAt
   */
  public OrderDto(java.lang.Integer count, java.lang.Long productId, java.lang.CharSequence status, java.lang.CharSequence sellerEmail, java.lang.CharSequence buyerEmail, java.lang.Long orderId, java.time.Instant expiresAt) {
    this.count = count;
    this.productId = productId;
    this.status = status;
    this.sellerEmail = sellerEmail;
    this.buyerEmail = buyerEmail;
    this.orderId = orderId;
    this.expiresAt = expiresAt.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return count;
    case 1: return productId;
    case 2: return status;
    case 3: return sellerEmail;
    case 4: return buyerEmail;
    case 5: return orderId;
    case 6: return expiresAt;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null,
      null,
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: count = (java.lang.Integer)value$; break;
    case 1: productId = (java.lang.Long)value$; break;
    case 2: status = (java.lang.CharSequence)value$; break;
    case 3: sellerEmail = (java.lang.CharSequence)value$; break;
    case 4: buyerEmail = (java.lang.CharSequence)value$; break;
    case 5: orderId = (java.lang.Long)value$; break;
    case 6: expiresAt = (java.time.Instant)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'count' field.
   * @return The value of the 'count' field.
   */
  public int getCount() {
    return count;
  }


  /**
   * Sets the value of the 'count' field.
   * @param value the value to set.
   */
  public void setCount(int value) {
    this.count = value;
  }

  /**
   * Gets the value of the 'productId' field.
   * @return The value of the 'productId' field.
   */
  public long getProductId() {
    return productId;
  }


  /**
   * Sets the value of the 'productId' field.
   * @param value the value to set.
   */
  public void setProductId(long value) {
    this.productId = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public java.lang.CharSequence getStatus() {
    return status;
  }


  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(java.lang.CharSequence value) {
    this.status = value;
  }

  /**
   * Gets the value of the 'sellerEmail' field.
   * @return The value of the 'sellerEmail' field.
   */
  public java.lang.CharSequence getSellerEmail() {
    return sellerEmail;
  }


  /**
   * Sets the value of the 'sellerEmail' field.
   * @param value the value to set.
   */
  public void setSellerEmail(java.lang.CharSequence value) {
    this.sellerEmail = value;
  }

  /**
   * Gets the value of the 'buyerEmail' field.
   * @return The value of the 'buyerEmail' field.
   */
  public java.lang.CharSequence getBuyerEmail() {
    return buyerEmail;
  }


  /**
   * Sets the value of the 'buyerEmail' field.
   * @param value the value to set.
   */
  public void setBuyerEmail(java.lang.CharSequence value) {
    this.buyerEmail = value;
  }

  /**
   * Gets the value of the 'orderId' field.
   * @return The value of the 'orderId' field.
   */
  public long getOrderId() {
    return orderId;
  }


  /**
   * Sets the value of the 'orderId' field.
   * @param value the value to set.
   */
  public void setOrderId(long value) {
    this.orderId = value;
  }

  /**
   * Gets the value of the 'expiresAt' field.
   * @return The value of the 'expiresAt' field.
   */
  public java.time.Instant getExpiresAt() {
    return expiresAt;
  }


  /**
   * Sets the value of the 'expiresAt' field.
   * @param value the value to set.
   */
  public void setExpiresAt(java.time.Instant value) {
    this.expiresAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Creates a new OrderDto RecordBuilder.
   * @return A new OrderDto RecordBuilder
   */
  public static com.sachet.OrderDto.Builder newBuilder() {
    return new com.sachet.OrderDto.Builder();
  }

  /**
   * Creates a new OrderDto RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new OrderDto RecordBuilder
   */
  public static com.sachet.OrderDto.Builder newBuilder(com.sachet.OrderDto.Builder other) {
    if (other == null) {
      return new com.sachet.OrderDto.Builder();
    } else {
      return new com.sachet.OrderDto.Builder(other);
    }
  }

  /**
   * Creates a new OrderDto RecordBuilder by copying an existing OrderDto instance.
   * @param other The existing instance to copy.
   * @return A new OrderDto RecordBuilder
   */
  public static com.sachet.OrderDto.Builder newBuilder(com.sachet.OrderDto other) {
    if (other == null) {
      return new com.sachet.OrderDto.Builder();
    } else {
      return new com.sachet.OrderDto.Builder(other);
    }
  }

  /**
   * RecordBuilder for OrderDto instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<OrderDto>
    implements org.apache.avro.data.RecordBuilder<OrderDto> {

    private int count;
    private long productId;
    private java.lang.CharSequence status;
    private java.lang.CharSequence sellerEmail;
    private java.lang.CharSequence buyerEmail;
    private long orderId;
    private java.time.Instant expiresAt;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.sachet.OrderDto.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.count)) {
        this.count = data().deepCopy(fields()[0].schema(), other.count);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.productId)) {
        this.productId = data().deepCopy(fields()[1].schema(), other.productId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.status)) {
        this.status = data().deepCopy(fields()[2].schema(), other.status);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.sellerEmail)) {
        this.sellerEmail = data().deepCopy(fields()[3].schema(), other.sellerEmail);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.buyerEmail)) {
        this.buyerEmail = data().deepCopy(fields()[4].schema(), other.buyerEmail);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.orderId)) {
        this.orderId = data().deepCopy(fields()[5].schema(), other.orderId);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.expiresAt)) {
        this.expiresAt = data().deepCopy(fields()[6].schema(), other.expiresAt);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
    }

    /**
     * Creates a Builder by copying an existing OrderDto instance
     * @param other The existing instance to copy.
     */
    private Builder(com.sachet.OrderDto other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.count)) {
        this.count = data().deepCopy(fields()[0].schema(), other.count);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.productId)) {
        this.productId = data().deepCopy(fields()[1].schema(), other.productId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.status)) {
        this.status = data().deepCopy(fields()[2].schema(), other.status);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.sellerEmail)) {
        this.sellerEmail = data().deepCopy(fields()[3].schema(), other.sellerEmail);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.buyerEmail)) {
        this.buyerEmail = data().deepCopy(fields()[4].schema(), other.buyerEmail);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.orderId)) {
        this.orderId = data().deepCopy(fields()[5].schema(), other.orderId);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.expiresAt)) {
        this.expiresAt = data().deepCopy(fields()[6].schema(), other.expiresAt);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'count' field.
      * @return The value.
      */
    public int getCount() {
      return count;
    }


    /**
      * Sets the value of the 'count' field.
      * @param value The value of 'count'.
      * @return This builder.
      */
    public com.sachet.OrderDto.Builder setCount(int value) {
      validate(fields()[0], value);
      this.count = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'count' field has been set.
      * @return True if the 'count' field has been set, false otherwise.
      */
    public boolean hasCount() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'count' field.
      * @return This builder.
      */
    public com.sachet.OrderDto.Builder clearCount() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'productId' field.
      * @return The value.
      */
    public long getProductId() {
      return productId;
    }


    /**
      * Sets the value of the 'productId' field.
      * @param value The value of 'productId'.
      * @return This builder.
      */
    public com.sachet.OrderDto.Builder setProductId(long value) {
      validate(fields()[1], value);
      this.productId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'productId' field has been set.
      * @return True if the 'productId' field has been set, false otherwise.
      */
    public boolean hasProductId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'productId' field.
      * @return This builder.
      */
    public com.sachet.OrderDto.Builder clearProductId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public java.lang.CharSequence getStatus() {
      return status;
    }


    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public com.sachet.OrderDto.Builder setStatus(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.status = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public com.sachet.OrderDto.Builder clearStatus() {
      status = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'sellerEmail' field.
      * @return The value.
      */
    public java.lang.CharSequence getSellerEmail() {
      return sellerEmail;
    }


    /**
      * Sets the value of the 'sellerEmail' field.
      * @param value The value of 'sellerEmail'.
      * @return This builder.
      */
    public com.sachet.OrderDto.Builder setSellerEmail(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.sellerEmail = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'sellerEmail' field has been set.
      * @return True if the 'sellerEmail' field has been set, false otherwise.
      */
    public boolean hasSellerEmail() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'sellerEmail' field.
      * @return This builder.
      */
    public com.sachet.OrderDto.Builder clearSellerEmail() {
      sellerEmail = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'buyerEmail' field.
      * @return The value.
      */
    public java.lang.CharSequence getBuyerEmail() {
      return buyerEmail;
    }


    /**
      * Sets the value of the 'buyerEmail' field.
      * @param value The value of 'buyerEmail'.
      * @return This builder.
      */
    public com.sachet.OrderDto.Builder setBuyerEmail(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.buyerEmail = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'buyerEmail' field has been set.
      * @return True if the 'buyerEmail' field has been set, false otherwise.
      */
    public boolean hasBuyerEmail() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'buyerEmail' field.
      * @return This builder.
      */
    public com.sachet.OrderDto.Builder clearBuyerEmail() {
      buyerEmail = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'orderId' field.
      * @return The value.
      */
    public long getOrderId() {
      return orderId;
    }


    /**
      * Sets the value of the 'orderId' field.
      * @param value The value of 'orderId'.
      * @return This builder.
      */
    public com.sachet.OrderDto.Builder setOrderId(long value) {
      validate(fields()[5], value);
      this.orderId = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'orderId' field has been set.
      * @return True if the 'orderId' field has been set, false otherwise.
      */
    public boolean hasOrderId() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'orderId' field.
      * @return This builder.
      */
    public com.sachet.OrderDto.Builder clearOrderId() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'expiresAt' field.
      * @return The value.
      */
    public java.time.Instant getExpiresAt() {
      return expiresAt;
    }


    /**
      * Sets the value of the 'expiresAt' field.
      * @param value The value of 'expiresAt'.
      * @return This builder.
      */
    public com.sachet.OrderDto.Builder setExpiresAt(java.time.Instant value) {
      validate(fields()[6], value);
      this.expiresAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'expiresAt' field has been set.
      * @return True if the 'expiresAt' field has been set, false otherwise.
      */
    public boolean hasExpiresAt() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'expiresAt' field.
      * @return This builder.
      */
    public com.sachet.OrderDto.Builder clearExpiresAt() {
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public OrderDto build() {
      try {
        OrderDto record = new OrderDto();
        record.count = fieldSetFlags()[0] ? this.count : (java.lang.Integer) defaultValue(fields()[0]);
        record.productId = fieldSetFlags()[1] ? this.productId : (java.lang.Long) defaultValue(fields()[1]);
        record.status = fieldSetFlags()[2] ? this.status : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.sellerEmail = fieldSetFlags()[3] ? this.sellerEmail : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.buyerEmail = fieldSetFlags()[4] ? this.buyerEmail : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.orderId = fieldSetFlags()[5] ? this.orderId : (java.lang.Long) defaultValue(fields()[5]);
        record.expiresAt = fieldSetFlags()[6] ? this.expiresAt : (java.time.Instant) defaultValue(fields()[6]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<OrderDto>
    WRITER$ = (org.apache.avro.io.DatumWriter<OrderDto>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<OrderDto>
    READER$ = (org.apache.avro.io.DatumReader<OrderDto>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










