{
    "namespace": "com.sachet",
    "type": "record",
    "name": "OrderDto",
    "fields": [
        {
            "name": "count",
            "type": "int"
        },
        {
            "name": "productId",
            "type": "long"
        },
        {
            "name": "status",
            "type": "string"
        },
        {
            "name": "sellerEmail",
            "type": "string"
        },
        {
            "name": "buyerEmail",
            "type": "string"
        },
        {
            "name": "orderId",
            "type": "long"
        },
        {
            "name": "expiresAt",
            "type": {
                "type": "long",
                "logicalType": "timestamp-millis",
                "default": null
            }
        }
    ]
}